apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # For local development/testing (minikube, kind, etc.)
  # For cloud providers, you may want to use a specific volume type
  hostPath:
    path: /data/postgres-data
    type: DirectoryOrCreate
  # Uncomment and use one of these for cloud providers instead:
  # 
  # For AWS EKS:
  # awsElasticBlockStore:
  #   volumeID: <volume-id>
  #   fsType: ext4
  #
  # For GCP GKE:
  # gcePersistentDisk:
  #   pdName: <disk-name>
  #   fsType: ext4
  #
  # For Azure AKS:
  # azureDisk:
  #   diskName: <disk-name>
  #   diskURI: <disk-uri>
  #   cachingMode: ReadWrite
  #   fsType: ext4

